import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:shimmer/shimmer.dart';
import 'package:task/src/core/consts/app_image.dart';
import 'package:task/src/features/favorit/presentation/bloc/favorite_bloc.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:task/src/features/movies/presentation/view/movies_page.dart';
part 'favorite_list.dart';
